# Generated by Django 4.2.4 on 2023-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="created_by",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="updated_by",
            field=models.URLField(blank=True, null=True),
        ),
    ]
